-- Seed script for form_fields table for school_info, demographics, curriculum, computerRoom, and resources

INSERT INTO form_fields (table_name, field_name, prompt, type, valuelist, field_width, required, visible) VALUES
  -- school_info
  ('school_info', 'moe_name',              'MOE School Name',                           'text',   NULL,      6,  0,  1),
  ('school_info', 'name',                  'Corrected School Name',                     'text',   NULL,      6,  1,  1),
  ('school_info', 'code',                  'MOE School Code',                           'text',   NULL,      6,  1,  1),
  ('school_info', 'address',               'School Address',                            'text',   NULL,     12,  1,  1),
  ('school_info', 'contact_person',         ' Name of Principal',                                 'text',   NULL,      6,  1,  1),
  ('school_info', 'telephone',             'Principal Phone',                           'phone',  NULL,      6,  1,  1),
  ('school_info', 'telephone_alt1',        'Alternate Phone 1',                         'phone',  NULL,      6,  0,  1),
  ('school_info', 'telephone_alt2',        'Alternate Phone 2',                         'phone',  NULL,      6,  0,  1),
  ('school_info', 'moe_email',             'MOE Email',                                 'email',  NULL,      6,  0,  1),
  ('school_info', 'email',                 'Principal Email',                           'email',  NULL,      6,  1,  1),
  ('school_info', 'email_alt',             'Alternate Email',                           'email',  NULL,      6,  0,  1),
  ('school_info', 'website',               'Website',                                   'text',   NULL,      6,  0,  1),
  ('school_info', 'year_opened',           'Year Opened',                               'num(1800-2050)', NULL, 6,  0,  1),
  ('school_info', 'longitude',             'Longitude',                                 'text',   NULL,      6,  0,  1),
  ('school_info', 'latitude',              'Latitude',                                  'text',   NULL,      6,  0,  1),
  ('school_info', 'district',              'District',                                  'dropdown','Belize,Cayo,Corozal,Orange Walk,Stann Creek,Toledo', 6,1,1),
  ('school_info', 'locality',              'Locality',                                  'dropdown','Rural,Urban', 6,1,1),
  ('school_info', 'type',                  'School Type',                               'dropdown','Preschool,Primary,Secondary,Tertiary,Vocational,Adult and Continuing,University',6,1,1),
  ('school_info', 'ownership',             'Ownership',                                 'dropdown', 'Advantist Schools, Anglican Schools, Assemblies Of God Schools, Baptist, Catholic Schools, Government Schools, Mennonite Schools - Church Group. Mennonite Schools - H&B, Mennonite Schools - Spanish Lookout, Methodist Schools, Nazarene Schools,Presbyterian Schools, Private Schools, U.E.C.B Schools, Other',      6,  0,  1),
  ('school_info', 'sector',                'Sector',                                    'dropdown','Government,Government Aided,Private,Specially Assisted',6,1,1),
  ('school_info', 'school_administrator_1','Administrator 1',                           'text',   NULL,  6,  0,  1),
  ('school_info', 'school_administrator_2','Administrator 2',                           'text',   NULL,  6,  0,  1),
  ('school_info', 'comments',              'Comments',                                  'text',   NULL,  12,  0,  1),

  -- demographics
  ('demographics', 'minutes_drive_from_road',         'How many minutes drive is your school from the main road?', 'num(0-120)', NULL, 6,1,1),
  ('demographics', 'principals_name',                 'Principal Name',                      'text',   NULL,      6,1,1),
  ('demographics', 'principals_telephone',            'Principal’s phone number (WhatsApp preferred)',                     'phone',  NULL,      6,1,1),
  ('demographics', 'principals_email',                'Principal’s email address', 'email',  NULL, 6,1,1),
  ('demographics', 'principals_computer',             'Does the principal have a good working computer that is not rented?','dropdown','Yes,No',6,0,1),
  ('demographics', 'number_of_students',              'Total number of students in your school', 'num(0-5000)', NULL,6,1,1),
  ('demographics', 'largest_class_size',              'Number of students in your largest classroom','num(0-500)', NULL, 6,0,1),
  ('demographics', 'number_of_buildings',             'Number of buildings at your school (not including storage buildings)','num(0-50)', NULL,6,0,1),
  ('demographics', 'number_of_buildings_with_internet','Buildings with Internet',             'num(0-50)', NULL,6,0,1),
  ('demographics', 'number_of_computer_labs',         'Number of computer labs / rooms in your school', 'dropdown', '0,1,2,3+',6,0,1),
  ('demographics', 'internet_provider',               'Internet Provider',                    'text',   NULL,      6, 0,  1),
  ('demographics', 'internet_speed_Mbps',             'Internet Speed (Mbps)',               'num(0-10000)', NULL,6,0,1),
  ('demographics', 'connection_method',               'Connection Method',                   'text',   NULL,      6, 0,  1),
  ('demographics', 'internet_stability',              'Internet Stability',                  'text',   NULL,      6, 0,  1),
  ('demographics', 'power_stability',                'Power Outages Per Week',              'num(0-168)', NULL,6,1,1),
  ('demographics', 'has_pta',                        'Has PTA/Support Group?',              'dropdown','Yes,No',   6,1,1),
  ('demographics', 'has_technician_to_maintain_computers','Technician for Computers',        'text',   NULL,      6, 0,  1),
  ('demographics', 'number_of_teachers',              'Number of Teachers',                  'num(0-500)', NULL,6,1,1),
  ('demographics', 'number_of_full_time_IT_teachers', 'Number of Full-Time IT Teachers',               'num(0-50)', NULL,6,0,1),
  ('demographics', 'number_of_teachers_that_also_teach_IT','Teachers Also Teaching IT',        'num(0-50)', NULL,6,0,1),
  ('demographics', 'number_of_teachers_that_have_laptops','Teachers with Laptops',             'num(0-500)', NULL,6,0,1),
  ('demographics', 'primary_IT_teacher_name',          'Primary IT Teacher Name',             'text',   NULL,      6,0,1),
  ('demographics', 'primary_IT_teacher_phone',         'Primary IT Teacher Phone',            'phone',  NULL,      6,0,1),
  ('demographics', 'primary_IT_teacher_email',         'Primary IT Teacher Email',            'email',  NULL,      6,0,1),
  ('demographics', 'percentage_of_students_who_have_personal_computers','% Students with Computers','num(0-100)',NULL,6,0,1),
  ('demographics', 'access_to_computers',             '% Students with Computer Access',     'num(0-100)',NULL,6,0,1),
  ('demographics', 'access_to_phones_for_school_work','% Students Using Phones for School Work','num(0-100)',NULL,6,0,1),
  ('demographics', 'comments',                        'Additional Comments',                 'text',   NULL,     12, 0,1),

  -- curriculum
  ('curriculum', 'keyboarding',                        'Does your school teach general keyboarding?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'computer_literacy',                 'Does your school teach computer literacy?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'word',                              'Does your school teach word processing such as Microsoft Word, LibreOffice/OpenOffice Write or Google Docs?',              'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'spread_sheet',                       'Does your school teach spreadsheets such as Excel, LibreOffice Calc, or Google Sheets?', 'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'data_base',                          'Does your school teach about databases such as MS Access, LibreOffice Base, MySQL?', 'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'slide_show',                         'Does your school teach slide show design such as: PowerPoint, LibreOffice Present, Google Slides?', 'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'google_workspace',                   'Does your school also teach Google Workspace such as Google Docs, Sheets, etc.?',             'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'software_suite',                     'Which software suite does your school prefer?','dropdown','Do not know,Microsoft Office,LibreOffice,OpenOffice,Google WorkSpace,Both Office and Workspace',6,0,1),
  ('curriculum', 'cloud_based_learning_tools',         'Does your school use other learning websites such as typing, spelling, math, etc.?',        'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'graphics_design',                    'Does your school teach graphics design tools such as Photoshop, Illustrator, Publisher, Canva, PosterMyWall or equivalent?',        'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'graphics_animation',                 'Does your school teach graphics animation such as Blender or equivalent?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'graphics_cad_program',               'Does your school teach graphics CAD tools such as AutoCad or equivalent?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'robotics',                           'Does your school teach robotics?' , 'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'code_dot_org',                       'Does your school use code.org?', 'dropdown','Yes,No',   6,1,1),
  ('curriculum', 'khan_accadamy',                     'Does your school use Khan Academy or similar online learning platforms?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'other_on_liine_local_education_tools','Other educational websites?','text', NULL,6,0,1),
  ('curriculum', 'formal_curriculum',                  'What formal computer related curriculum does your school use if any?',     'text',   NULL,      6,0,1),
  ('curriculum', 'local_curriculum',                   'What locally generated computer related curriculum does your school use?',      'text',   NULL,      6,0,1),
  ('curriculum', 'rachel_server',                      'Does your school participate in the Rachel server project?','dropdown','Yes,No',   6,1,1),
  ('curriculum', 'other',                              'What other computer related teaching tools do you use that were not mentioned above?',                'text',   NULL,     12, 0,1),
  ('curriculum', 'comments',                           'CommentsDo you have any comments about the above information',                             'text',   NULL,     12, 0,1),

  -- computerRoom
  ('computerRoom', 'wired_for_lab',                    'Has your computer room been wired expressly for a computer lab?',             'dropdown','Yes,No', 6,1,1),
  ('computerRoom', 'electrical',                       'Does your computer room have a dedicated electrical service panel in the computer room?',          'dropdown','Yes,No', 6,1,1),
  ('computerRoom', 'electrical_ground',                'Is there a quality ground wire connected to a ground rod?',                'dropdown','Yes,No', 6,1,1),
  ('computerRoom', 'electrical_outlets',               'How many electrical outlets are in the computer room?',            'num(0-100)',NULL,6,1,1),
  ('computerRoom', 'air_condition',                    'How many working air conditioners does your computer lab have?',             'num(0-50)',NULL,6,1,1),
  ('computerRoom', 'partition_security',               'Are all 4 walls in your computer room concrete including the partition to the next room?', 'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'ceiling_secure',                   'Is your computer lab ceiling constructed of concrete or steel with no open spaces and secured from a thief climbing over the partitioned wall?',         'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'windows_secure',                   'Are all the windows removed and blocked, or have strong burglar bars installed?',          'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'lighting',                         'Is the lighting in your computer room sufficient (even when all windows are blocked)?',                'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'location',                         'Is your computer room located at the end of your building (i.e. with 3 outside walls)?',               'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'location_floor',                   'Is your computer room located on the first floor?',                'dropdown','Yes,No',   6,1,1),
  ('computerRoom', 'comments',                         'Do you have any comments about the above information',                 'text',   NULL,     12, 0,1),

  -- resources
  ('resources', 'number_seats',                       'Student station capacity',            'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_working',                    'Working desktop computers',           'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_not_working',                'Non-working desktops',                'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_age',                        'Desktop age (years)',                 'num(0-50)',NULL,6,1,1),
  ('resources', 'desktop_ownership',                  'Desktop ownership duration (years)',  'num(0-50)',NULL,6,1,1),
  ('resources', 'desktop_monitors',                   'Working monitors',                    'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_keyboards',                  'Working keyboards',                   'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_mice',                       'Working mice',                        'num(0-1000)',NULL,6,1,1),
  ('resources', 'desktop_comments',                   'Desktop reliability comments',        'text',   NULL,     12, 0,1),
  ('resources', 'chromebooks_working',                'Working Chromebooks',                 'num(0-1000)',NULL,6,1,1),
  ('resources', 'chromebooks_broken',                 'Chromebooks broken (3yr)',            'num(0-1000)',NULL,6,1,1),
  ('resources', 'chromebooks_lost',                   'Chromebooks lost (2yr)',              'num(0-1000)',NULL,6,1,1),
  ('resources', 'chromebooks_comments',               'Chromebook reliability comments',      'text',   NULL,     12, 0,1),
  ('resources', 'tablets_working',                   'Working tablets',                     'num(0-1000)',NULL,6,1,1),
  ('resources', 'tablets_broken',                    'Tablets broken (2yr)',                'num(0-1000)',NULL,6,1,1),
  ('resources', 'tablets_lost',                      'Tablets lost (2yr)',                  'num(0-1000)',NULL,6,1,1),
  ('resources', 'tablets_comments',                  'Tablet reliability comments',          'text',   NULL,     12, 0,1),
  ('resources', 'old_computers_work',                'Plan for old working computers',      'text',   NULL,      6, 0,1),
  ('resources', 'old_computers_broken',              'Plan for broken computers',           'text',   NULL,      6, 0,1),
  ('resources', 'comments',                          'Additional comments',                 'text',   NULL,     12, 0,1)
ON DUPLICATE KEY UPDATE
  prompt = VALUES(prompt),
  type = VALUES(type),
  valuelist = VALUES(valuelist),
  field_width = VALUES(field_width),
  required = VALUES(required),
  visible = VALUES(visible);
